export const GET_PEOPLE = 'GET_PEOPLE'
export const GET_PEOPLE_SUCCESS = 'GET_PEOPLE_SUCCESS'
export const GET_PEOPLE_FAILURE = 'GET_PEOPLE_FAILURE'

export const REMOVE_PEOPLE = 'REMOVE_PEOPLE'
export const REMOVE_PEOPLE_SUCCESS = 'REMOVE_PEOPLE_SUCCESS'
export const REMOVE_PEOPLE_FAILURE = 'REMOVE_PEOPLE_FAILURE'

export const SEARCH_PEOPLE = 'SEARCH_PEOPLE'
